services:
  - type: web
    name: matcheval-frontend
    env: static
    rootDir: coreui-free-angular-admin-template-main
    buildCommand: npm ci --legacy-peer-deps && npm run build
    staticPublishPath: dist/coreui-free-angular-admin-template
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
