services:
  - type: web
    name: matcheval-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: dist/coreui-free-angular-admin-template
    routes:
      - type: rewrite
        source: /*
        destination: /index.html